rules:
  - path: /api/oauth/token
    query_params:
      grant_type: client_credentials
    methods: ['POST']
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |
          {"access_token":"xxxx","expires_in":3600,"token_type":"Bearer","refresh_token":"yyyy"}
  - path: /api/v1/computers-inventory
    methods: ["GET"]
    query_params:
      page-size: 100
      page: 0
    responses:
      - status_code: 200
        body: "{\n  \"totalCount\": 8,\n  \"results\": [\n    {\n      \"id\":\"3\",\n      \"udid\":\"5982CE36-4526-580B-B4B9-ECC6782535BC\",\n      \"general\":{\n        \"name\":\"acme-C07DM3AZQ6NV\",\n        \"lastReportedIp\":\"10.122.26.87\",\n        \"lastIpAddress\":\"10.122.26.87\",\n        \"jamfBinaryVersion\":\"11.4.1-t1712591696\",\n        \"platform\":\"Mac\",\n        \"barcode1\":\"null\",\n        \"remoteManagement\":{\n          \"managed\":true\n        },\n        \"supervised\":false,\n        \"mdmCapable\":{\n          \"capable\":false,\n          \"capableUsers\":[\n            \n          ]\n        },\n        \"reportDate\":\"2024-06-19T15:54:37.692Z\",\n        \"lastContactTime\":\"2024-04-18T14:26:51.514Z\",\n        \"lastEnrolledDate\":\"2023-02-22T10:46:17.199Z\",\n        \"initialEntryDate\":\"2024-06-19\",\n        \"site\":{\n          \"id\":\"-1\",\n          \"name\":\"None\"\n        },\n        \"itunesStoreAccountActive\":false,\n        \"enrolledViaAutomatedDeviceEnrollment\":false,\n        \"userApprovedMdm\":false,\n        \"declarativeDeviceManagementEnabled\":false,\n        \"managementId\":\"1a59c510-b3a9-41cb-8afa-3d4187ac60d0\",\n        \"extensionAttributes\":[\n          \n        ]\n      },\n      \"diskEncryption\":null,\n      \"localUserAccounts\":null,\n      \"purchasing\":null,\n      \"printers\":null,\n      \"storage\":null,\n      \"applications\":null,\n      \"userAndLocation\":null,\n      \"configurationProfiles\":null,\n      \"services\":null,\n      \"plugins\":null,\n      \"hardware\":null,\n      \"certificates\":null,\n      \"attachments\":null,\n      \"packageReceipts\":null,\n      \"fonts\":null,\n      \"security\":null,\n      \"operatingSystem\":null,\n      \"licensedSoftware\":null,\n      \"softwareUpdates\":null,\n      \"groupMemberships\":null,\n      \"extensionAttributes\":null,\n      \"contentCaching\":null,\n      \"ibeacons\":null\n    }\n  ]\n}"
